apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: processorAlertFlag1
spec:
  topic: processorAlertFlag1
  route: /processor/alertflag
  pubsubname: pubsub
  metadata:
    name:  ttlInSeconds
    value: 600
